export const dataInDropdown = {
    imageTypes: ["Photo", "Empty Room", "Sketch"],
    roomTypes: [
      "Living Room",
      "Bedroom",
      "Kitchen",
      "Dining Room",
      "Bathroom",
    ],
    styles: [
      "Modern",
      "Contemporary",
      "Minimalist",
      "Scandinavian",
      "Industrial",
      "Traditional",
      "Transitional",
      "Mid-Century Modern",
      "Rustic",
      "Farmhouse",
      "Bohemian (Boho)",
      "Coastal / Beach",
      "Mediterranean",
      "Art Deco",
      "Eclectic",
      "Vintage",
      "Gothic",
      "Japanese Zen",
      "Tropical",
      "Urban / Loft",
      "Victorian",
      "Colonial",
      "French Country",
      "Hollywood Regency",
      "Shabby Chic",
    ],
  };
  